### ISSUE TITLE
Add more linters to the golangci-lint test

### ISSUE THREAD

**Issue by AryanGodara** [Mainflux/mainflux-lite#1774]
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No
2. Describe the feature you are requesting, as well as the possible use case(s) for it.
#1729 Added added more linters to the golangci-lint, updated it, and fixed all the errors in the repo. Although, there is still scope to add even more linters, but they must be researched and tested locally before adding to the master branch.
3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
Should have

**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - tests
   - code refactor
   - research
   - tooling

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
Should have

**Comment by rodneyosodo** [comment]
Enable `go-header`

This is the sample  linter-settings that can be used to check that every file has a license

```yaml
linters-settings:
  goheader:
    template: |-
      Copyright (c) Mainflux
      SPDX-License-Identifier: Apache-2.0
```
